// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      //my mistake macOS ko select nahi krna tha while choosing option from CLI  
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxAk2unoowSu_2FSNpLGrhsheKah8OPH0',
    appId: '1:283138086066:web:7ceaaecdb969d09b2c65ab',
    messagingSenderId: '283138086066',
    projectId: 'reddit-clone-7d308',
    authDomain: 'reddit-clone-7d308.firebaseapp.com',
    storageBucket: 'reddit-clone-7d308.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAriQHt9oEw_wiffsI8MRJof3fDvkwWI50',
    appId: '1:283138086066:android:6ce3343bc7c7ba2a2c65ab',
    messagingSenderId: '283138086066',
    projectId: 'reddit-clone-7d308',
    storageBucket: 'reddit-clone-7d308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-OPasXZUsjeCGk6GVsoS9_2gfWO9G5MY',
    appId: '1:283138086066:ios:944fba45cac28a362c65ab',
    messagingSenderId: '283138086066',
    projectId: 'reddit-clone-7d308',
    storageBucket: 'reddit-clone-7d308.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyD-OPasXZUsjeCGk6GVsoS9_2gfWO9G5MY',
  //   appId: '1:283138086066:ios:a14267b7ab798c0c2c65ab',
  //   messagingSenderId: '283138086066',
  //   projectId: 'reddit-clone-7d308',
  //   storageBucket: 'reddit-clone-7d308.appspot.com',
  //   iosBundleId: 'com.example.redditClone.RunnerTests',
  // );
}
